"""Calculate supplementary heatwave factors from the output of main code 1.

This second-stage script does not recalculate temperature thresholds or re-identify heatwaves. It reads the mutually exclusive DHW, NHW and CHW daily
indicators produced by main code 1 and calculates:

1. daily exceeded quantity (EQ), event-day number, total event duration and cumulative excess heatwave index (CEHWI);
2. an event-level table containing event timing, duration and intensity; and
3. an annual table containing event frequency, heatwave days, mean/maximum duration and annual intensity statistics.


The annual event count assigns an event to the year in which it starts. Annual heatwave days and daily intensity statistics are calculated by calendar year.
Consequently, an event spanning 31 December is counted once but contributes daily observations to both calendar years.

"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


DHW = "DHW"
NHW = "NHW"
CHW = "CHW"
EVENT_TYPES = (DHW, NHW, CHW)


def parse_args() -> argparse.Namespace:
    """Parse command-line options."""
    parser = argparse.ArgumentParser(
        description=(
            "Calculate daily, event-level and annual heatwave factors from the "
            "standardized CSV files produced by main code 1."
        )
    )
    parser.add_argument(
        "--grid-list",
        type=Path,
        help="CSV containing the grid-cell identifiers.",
    )
    parser.add_argument(
        "--id-column",
        default="FID_USA_fi",
        help="Identifier column in --grid-list (default: FID_USA_fi).",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        help="Directory containing the daily outputs from main code 1.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Root directory for daily, event and annual factor outputs.",
    )
    parser.add_argument(
        "--input-template",
        default="{id}_temperature_heatwaves.csv",
        help=(
            "Input filename template generated by main code 1 "
            "(default: {id}_temperature_heatwaves.csv)."
        ),
    )
    parser.add_argument(
        "--start-year",
        type=int,
        default=2010,
        help="First reporting year (default: 2010).",
    )
    parser.add_argument(
        "--end-year",
        type=int,
        default=2024,
        help="Last reporting year, inclusive (default: 2024).",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="Run built-in synthetic validation tests and exit.",
    )
    return parser.parse_args()


def _normalise_grid_ids(values: Iterable[object]) -> list[str]:
    """Convert grid identifiers to stable filename strings."""
    identifiers: list[str] = []
    for value in values:
        if pd.isna(value):
            continue
        if isinstance(value, (int, np.integer)):
            identifiers.append(str(int(value)))
        elif isinstance(value, (float, np.floating)) and float(value).is_integer():
            identifiers.append(str(int(value)))
        else:
            identifiers.append(str(value).strip())
    return identifiers


def load_main_output(path: Path) -> pd.DataFrame:
    """Load and validate one daily output file produced by main code 1."""
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")

    data = pd.read_csv(path, index_col=0)
    dates = pd.to_datetime(data.index, errors="coerce").normalize()
    if dates.isna().any():
        raise ValueError(f"{path} contains invalid date values.")

    data.index = dates
    data.index.name = "date"
    data = data.sort_index()
    if data.index.duplicated().any():
        duplicate = data.index[data.index.duplicated()][0]
        raise ValueError(f"{path} contains duplicate date {duplicate.date()}.")

    required = {
        "Tmax_C",
        "Tmin_C",
        "Tmax_threshold_95_C",
        "Tmin_threshold_95_C",
        DHW,
        NHW,
        CHW,
    }
    missing = required.difference(data.columns)
    if missing:
        raise KeyError(
            f"{path} is missing required column(s): {sorted(missing)}"
        )

    numeric_columns = [
        "Tmax_C",
        "Tmin_C",
        "Tmax_threshold_95_C",
        "Tmin_threshold_95_C",
        DHW,
        NHW,
        CHW,
    ]
    for column in numeric_columns:
        data[column] = pd.to_numeric(data[column], errors="coerce")

    for event_type in EVENT_TYPES:
        if not data[event_type].dropna().isin([0, 1]).all():
            raise ValueError(f"Column {event_type} must contain only 0 and 1.")
        data[event_type] = data[event_type].fillna(0).astype("int8")

    overlap_count = int(data[list(EVENT_TYPES)].sum(axis=1).gt(1).sum())
    if overlap_count:
        raise ValueError(
            f"{path} contains {overlap_count} row(s) with non-mutually-exclusive "
            "DHW, NHW and CHW indicators."
        )

    if "heatwave_type" in data.columns:
        expected_type = pd.Series("NONE", index=data.index, dtype="object")
        for event_type in EVENT_TYPES:
            expected_type.loc[data[event_type].eq(1)] = event_type
        inconsistent = data["heatwave_type"].fillna("NONE").ne(expected_type)
        if inconsistent.any():
            first_date = inconsistent[inconsistent].index[0]
            raise ValueError(
                f"heatwave_type and binary indicators disagree on {first_date.date()}."
            )

    return data


def _event_metadata(
    event_flag: pd.Series,
) -> tuple[pd.Series, pd.Series, pd.Series]:
    """Return event ID, day within event and total duration for a binary flag."""
    is_event = event_flag.eq(1)
    date_gap = event_flag.index.to_series().diff().ne(pd.Timedelta(days=1))
    event_start = is_event & (~is_event.shift(fill_value=False) | date_gap)
    event_id = event_start.cumsum().where(is_event).astype("Int64")

    event_day = pd.Series(pd.NA, index=event_flag.index, dtype="Int64")
    duration = pd.Series(0, index=event_flag.index, dtype="int64")
    if is_event.any():
        event_day.loc[is_event] = (
            event_flag.loc[is_event]
            .groupby(event_id.loc[is_event], sort=False)
            .cumcount()
            .add(1)
            .astype("int64")
        )
        duration.loc[is_event] = (
            event_flag.loc[is_event]
            .groupby(event_id.loc[is_event], sort=False)
            .transform("size")
            .astype("int64")
        )
    return event_id, event_day, duration


def calculate_daily_factors(data: pd.DataFrame) -> pd.DataFrame:
    """Calculate EQ, CEHWI and event metadata without redefining heatwaves."""
    result = data.copy()

    # Recalculate EQ from the final mutually exclusive heatwave classification.
    # Non-event days are explicitly set to zero.
    result["EQ_DHW_C"] = np.where(
        result[DHW].eq(1),
        result["Tmax_C"] - result["Tmax_threshold_95_C"],
        0.0,
    )
    result["EQ_NHW_C"] = np.where(
        result[NHW].eq(1),
        result["Tmin_C"] - result["Tmin_threshold_95_C"],
        0.0,
    )
    result["EQ_CHW_C"] = np.where(
        result[CHW].eq(1),
        (
            (result["Tmax_C"] - result["Tmax_threshold_95_C"])
            + (result["Tmin_C"] - result["Tmin_threshold_95_C"])
        )
        / 2.0,
        0.0,
    )


    for event_type in EVENT_TYPES:
        eq_column = f"EQ_{event_type}_C"
        invalid = result[event_type].eq(1) & result[eq_column].lt(-1e-10)
        if invalid.any():
            first_date = invalid[invalid].index[0]
            raise ValueError(
                f"Negative {eq_column} on identified {event_type} day "
                f"{first_date.date()}. Check the main-code output."
            )

    # Build events from the final mutually exclusive types. CHW is retained even

    for event_type in EVENT_TYPES:
        event_id, event_day, duration = _event_metadata(result[event_type])
        event_id_column = f"{event_type}_event_id"
        event_day_column = f"{event_type}_event_day"
        duration_column = f"{event_type}_duration_days"
        eq_column = f"EQ_{event_type}_C"
        cehwi_column = f"CEHWI_{event_type}_C_days"
        total_column = f"{event_type}_event_CEHWI_C_days"

        result[event_id_column] = event_id
        result[event_day_column] = event_day
        result[duration_column] = duration
        result[cehwi_column] = 0.0
        result[total_column] = 0.0

        is_event = result[event_type].eq(1)
        if is_event.any():
            grouped_eq = result.loc[is_event].groupby(
                event_id.loc[is_event], sort=False
            )[eq_column]
            result.loc[is_event, cehwi_column] = grouped_eq.cumsum()
            result.loc[is_event, total_column] = grouped_eq.transform("sum")

    return result


def build_event_summary(daily: pd.DataFrame, grid_id: str) -> pd.DataFrame:
    """Create one row for each continuous final-type heatwave event."""
    records: list[dict[str, object]] = []
    for event_type in EVENT_TYPES:
        event_id_column = f"{event_type}_event_id"
        eq_column = f"EQ_{event_type}_C"
        cehwi_column = f"CEHWI_{event_type}_C_days"
        event_rows = daily.loc[daily[event_type].eq(1)]

        for event_id, group in event_rows.groupby(event_id_column, sort=True):
            start_date = group.index[0]
            end_date = group.index[-1]
            event_cehwi = float(group[cehwi_column].iloc[-1])
            summed_eq = float(group[eq_column].sum())
            if not np.isclose(event_cehwi, summed_eq, equal_nan=False):
                raise AssertionError(
                    f"CEHWI accumulation failed for grid {grid_id}, "
                    f"{event_type} event {event_id}."
                )

            records.append(
                {
                    "grid_id": grid_id,
                    "heatwave_type": event_type,
                    "event_id": int(event_id),
                    "start_date": start_date,
                    "end_date": end_date,
                    "start_year": int(start_date.year),
                    "end_year": int(end_date.year),
                    "duration_days": int(len(group)),
                    "mean_daily_EQ_C": float(group[eq_column].mean()),
                    "maximum_daily_EQ_C": float(group[eq_column].max()),
                    "event_CEHWI_C_days": event_cehwi,
                }
            )

    columns = [
        "grid_id",
        "heatwave_type",
        "event_id",
        "start_date",
        "end_date",
        "start_year",
        "end_year",
        "duration_days",
        "mean_daily_EQ_C",
        "maximum_daily_EQ_C",
        "event_CEHWI_C_days",
    ]
    return pd.DataFrame.from_records(records, columns=columns)


def build_annual_summary(
    daily: pd.DataFrame,
    events: pd.DataFrame,
    grid_id: str,
    start_year: int,
    end_year: int,
) -> pd.DataFrame:
    """Summarize frequency, duration and intensity for each year and type."""
    records: list[dict[str, object]] = []

    for year in range(start_year, end_year + 1):
        year_rows = daily.loc[daily.index.year == year]
        for event_type in EVENT_TYPES:
            event_days = year_rows.loc[year_rows[event_type].eq(1)]
            year_events = events.loc[
                events["heatwave_type"].eq(event_type)
                & events["start_year"].eq(year)
            ]
            eq_column = f"EQ_{event_type}_C"
            cehwi_column = f"CEHWI_{event_type}_C_days"

            records.append(
                {
                    "grid_id": grid_id,
                    "year": year,
                    "heatwave_type": event_type,
                    "event_count": int(len(year_events)),
                    "heatwave_days": int(len(event_days)),
                    "mean_event_duration_days": (
                        float(year_events["duration_days"].mean())
                        if not year_events.empty
                        else np.nan
                    ),
                    "median_event_duration_days": (
                        float(year_events["duration_days"].median())
                        if not year_events.empty
                        else np.nan
                    ),
                    "maximum_event_duration_days": (
                        int(year_events["duration_days"].max())
                        if not year_events.empty
                        else np.nan
                    ),
                    "annual_sum_daily_EQ_C_days": float(event_days[eq_column].sum()),
                    "mean_daily_EQ_C": (
                        float(event_days[eq_column].mean())
                        if not event_days.empty
                        else np.nan
                    ),
                    "maximum_daily_EQ_C": (
                        float(event_days[eq_column].max())
                        if not event_days.empty
                        else np.nan
                    ),
                    "mean_daily_CEHWI_C_days": (
                        float(event_days[cehwi_column].mean())
                        if not event_days.empty
                        else np.nan
                    ),
                    "maximum_daily_CEHWI_C_days": (
                        float(event_days[cehwi_column].max())
                        if not event_days.empty
                        else np.nan
                    ),
                    "mean_event_CEHWI_C_days": (
                        float(year_events["event_CEHWI_C_days"].mean())
                        if not year_events.empty
                        else np.nan
                    ),
                    "maximum_event_CEHWI_C_days": (
                        float(year_events["event_CEHWI_C_days"].max())
                        if not year_events.empty
                        else np.nan
                    ),
                    "annual_sum_event_CEHWI_C_days": float(
                        year_events["event_CEHWI_C_days"].sum()
                    ),
                }
            )

    return pd.DataFrame.from_records(records)


def process_grid(
    grid_id: str,
    input_dir: Path,
    output_dir: Path,
    input_template: str,
    start_year: int,
    end_year: int,
) -> tuple[Path, Path, Path, pd.DataFrame, pd.DataFrame]:
    """Calculate and save daily, event and annual factors for one grid cell."""
    input_path = input_dir / input_template.format(id=grid_id)
    source = load_main_output(input_path)
    reporting_data = source.loc[
        (source.index.year >= start_year) & (source.index.year <= end_year)
    ].copy()
    if reporting_data.empty:
        raise ValueError(
            f"No observations for {start_year}-{end_year} in {input_path}."
        )

    daily = calculate_daily_factors(reporting_data)
    events = build_event_summary(daily, grid_id)
    annual = build_annual_summary(
        daily, events, grid_id, start_year=start_year, end_year=end_year
    )

    daily_dir = output_dir / "daily"
    event_dir = output_dir / "events"
    annual_dir = output_dir / "annual"
    for directory in (daily_dir, event_dir, annual_dir):
        directory.mkdir(parents=True, exist_ok=True)

    daily_path = daily_dir / f"{grid_id}_daily_heatwave_factors.csv"
    event_path = event_dir / f"{grid_id}_heatwave_events.csv"
    annual_path = annual_dir / f"{grid_id}_annual_heatwave_factors.csv"
    daily.to_csv(daily_path, index=True, date_format="%Y-%m-%d")
    events.to_csv(event_path, index=False, date_format="%Y-%m-%d")
    annual.to_csv(annual_path, index=False)
    return daily_path, event_path, annual_path, events, annual


def run_self_test() -> None:
    """Validate compound EQ, event segmentation, duration and annual summaries."""
    dates = pd.date_range("2010-07-01", periods=8, freq="D")
    test_data = pd.DataFrame(
        {
            "Tmax_C": [26, 26, 28, 20, 20, 20, 28, 20],
            "Tmin_C": [20, 20, 26, 27, 27, 20, 26, 20],
            "Tmax_threshold_95_C": [24.0] * 8,
            "Tmin_threshold_95_C": [24.0] * 8,
            DHW: [1, 1, 0, 0, 0, 0, 0, 0],
            NHW: [0, 0, 0, 1, 1, 0, 0, 0],
            CHW: [0, 0, 1, 0, 0, 0, 1, 0],
        },
        index=dates,
    )

    daily = calculate_daily_factors(test_data)
    events = build_event_summary(daily, "test_grid")
    annual = build_annual_summary(daily, events, "test_grid", 2010, 2010)

    assert daily.loc["2010-07-01", "DHW_duration_days"] == 2
    assert daily.loc["2010-07-03", "CHW_duration_days"] == 1
    assert daily.loc["2010-07-07", "CHW_event_id"] == 2
    assert np.isclose(daily.loc["2010-07-03", "EQ_CHW_C"], 3.0)
    assert np.isclose(daily.loc["2010-07-03", "CEHWI_CHW_C_days"], 3.0)
    assert np.isclose(daily.loc["2010-07-07", "CEHWI_CHW_C_days"], 3.0)

    chw_events = events.loc[events["heatwave_type"].eq(CHW)]
    assert len(chw_events) == 2
    assert chw_events["duration_days"].tolist() == [1, 1]

    chw_annual = annual.loc[annual["heatwave_type"].eq(CHW)].iloc[0]
    assert chw_annual["event_count"] == 2
    assert chw_annual["heatwave_days"] == 2
    assert np.isclose(chw_annual["mean_event_duration_days"], 1.0)
    assert np.isclose(chw_annual["annual_sum_event_CEHWI_C_days"], 6.0)

    print("All supplementary heatwave-factor tests passed.")


def main() -> None:
    """Run the batch workflow."""
    args = parse_args()
    if args.self_test:
        run_self_test()
        return

    if args.end_year < args.start_year:
        raise ValueError("--end-year must be greater than or equal to --start-year.")

    missing_paths = [
        option
        for option, value in (
            ("--grid-list", args.grid_list),
            ("--input-dir", args.input_dir),
            ("--output-dir", args.output_dir),
        )
        if value is None
    ]
    if missing_paths:
        raise SystemExit(
            "The following arguments are required for batch processing: "
            + ", ".join(missing_paths)
        )

    grid_table = pd.read_csv(args.grid_list)
    if args.id_column not in grid_table.columns:
        raise KeyError(
            f"Column '{args.id_column}' is absent from {args.grid_list}. "
            f"Available columns: {list(grid_table.columns)}"
        )
    grid_ids = _normalise_grid_ids(grid_table[args.id_column])
    if not grid_ids:
        raise ValueError("No valid grid-cell identifiers were found.")

    all_events: list[pd.DataFrame] = []
    all_annual: list[pd.DataFrame] = []
    failures: list[tuple[str, str]] = []

    for position, grid_id in enumerate(grid_ids, start=1):
        try:
            daily_path, event_path, annual_path, events, annual = process_grid(
                grid_id=grid_id,
                input_dir=args.input_dir,
                output_dir=args.output_dir,
                input_template=args.input_template,
                start_year=args.start_year,
                end_year=args.end_year,
            )
            all_events.append(events)
            all_annual.append(annual)
            print(
                f"[{position}/{len(grid_ids)}] Wrote {daily_path}, "
                f"{event_path} and {annual_path}"
            )
        except Exception as exc:  # Continue processing the remaining grid cells.
            failures.append((grid_id, str(exc)))
            print(f"[{position}/{len(grid_ids)}] FAILED grid {grid_id}: {exc}")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    if all_events:
        pd.concat(all_events, ignore_index=True).to_csv(
            args.output_dir / "all_grid_heatwave_events.csv", index=False
        )
    if all_annual:
        pd.concat(all_annual, ignore_index=True).to_csv(
            args.output_dir / "all_grid_annual_heatwave_factors.csv", index=False
        )

    if failures:
        failure_path = args.output_dir / "failed_grid_cells.csv"
        pd.DataFrame(failures, columns=[args.id_column, "error"]).to_csv(
            failure_path, index=False
        )
        raise RuntimeError(
            f"{len(failures)} grid cell(s) failed. See {failure_path} for details."
        )


if __name__ == "__main__":
    main()
